---
title: "Assignment 11: Personalized Recommender"
author: "Desiree Thomas"
format: html
editor: visual
---

## Approach

Goal of this project:

In a previous assignment we assigned the task of creating a non-personalized recommendations using a Global Baseline Estimate. In that assignment, I used synthetic data generated by Google Gemini's LLM, to create a dataset of 75 unique users with Profile Id's and a 1-5 rating for 6 films they may have seen.

I will use this survey data to create a personalized recommendation algorithm of my choice. My initial approach to this task is to use a User-Based Collaborative Filtering (UBCF) through a package such as recommenderlab, found in R. I chose this package due to the supposed ease of start due to my inexperience and the time line in which this deliverable must be created, tested and submitted. I chose UBCF over Content-Based Filtering due to the Survey data not containing data such as genre, directors, etc; this led to the rejection of an item based recommendation algorithm.

Planned Implementation:

Since recommender algorithms use linear algebra across matrices and not long-format data, I will need to convert the data into a sparse matrix. The package I am planning to use, uses the object, realRatingMatrix. To get the data into this format, I will need to isolate the ratings that are input as '1', '2', '3', '4' or '5'. The data (movies) that is missing will be the unrated data and cannot be passed as NA values.

The beginning steps will be the simplest to implement, importing the CSV, cleaning out NAs, subsetting the data frame to specific columns, and then using coercion. A bit more difficult: I will train the UBCF model to identify other users with a similar rating history and then use their scores to estimate what the target user would think of movies they have not watched yet.

My recommender will output predicted ratings for all of the un-rated movies. Though the assignment calls for a ranking of the top 5 Since there are only 6 movies total, I will set it to predict the magnitude of the preference/5 (ex. 3.5/5 or 2/5).

To evaluate the model, I am planning to use K-fold cross-validation (I still need to do more research on this as it is new-to-me). This will them measure the Root Mean Square. This withholds a portion of the actual user ratings and compares them to the model's predictions, which will allow me to objectively quantify its accuracy.

Anticipated Challenges:

Some of the challenges I anticipate during this assignment are due to the very small size of my data. Due to this, I will have to focus on the rating prediction accuracy. There are also a lot of missing ratings, which may damper my attempts at collaborative filtering. Cold starting was a challenge in the original Global Baseline Estimate and may return in this project. Evaluation sensitivity may also be a challenge as well. Finally, due to my lack of experience in recommender systems, I will have to do a lot of research and learn how to successfully complete the assignment within the timeframe of the deliverable.
